version: '3'

services:
  # Application Service
  app:
    image: travelio-user-service:latest
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - postgresdb

  # PostgreSQL Service
  postgresdb:
    image: postgres:13
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret


